hello_world_job:
  runs-on: ubuntu-latest
  name: A job to say hello
  steps:
  - name: Hello world action step
    id: hello
    uses: lmiguelmarsan/hello-world-action@v1
    with:
      who-to-greet: 'lmiguelmarsan'
  - name: Get the output time
    run: echo "The time was ${{ steps.hello.outputs.time }}"
